/**
 * AutoCompactor — LLM-based conversation summarization with hysteresis tracking.
 *
 * When the conversation exceeds the profile's token budget trigger ratio,
 * early messages are replaced with a structured summary generated by a
 * dedicated (cheaper) LLM call. Recent turns are preserved intact.
 *
 * Extracted from ContextCompactor.compactConversation() with enhancements:
 *   - Hysteresis tracking: prevents repeated compaction attempts when
 *     the context is already minimal.
 *   - Compact slot model: uses `compact` slot (haiku → model fallback)
 *     for cheaper summarization calls.
 *
 * Mirrors Claude Code's auto-compact (src/services/compact/autoCompact.ts).
 */

import { estimateMessagesTokens, isOverBudget } from './token-counter'
import { COMPACT_SYSTEM_PROMPT, COMPACT_USER_PROMPT } from './compact-prompt'
import type { LLMMessage } from '../llm/ModelProvider'
import type { AgentProfile } from '../profile/AgentProfile'
import { modelProviderRegistry } from '../llm/ModelProviderRegistry'
import { loadLLMConfig } from '../llm/AttaSettingsLoader'
import { ModelResolver } from '../llm/ModelResolver'
import { COMPACT_MSG_TRUNCATE_CHARS } from '../../../shared/constants'

// ── Types ──

export interface AutoCompactResult {
  /** Messages after compaction (summary + recent turns). */
  messages: LLMMessage[]
  /** Generated summary text. */
  summary: string
  /** Estimated tokens freed. */
  tokensFreed: number
  /** Number of messages compacted away. */
  compressedCount: number
  /** Whether compaction was actually performed. */
  didCompact: boolean
}

export interface AutoCompactOptions {
  /** Model override for the compaction call (uses compact slot by default). */
  compactModel?: string
  /** Provider ID for slot resolution. */
  providerId?: string
}

/**
 * Hysteresis tracking — prevents thrashing when context is already minimal.
 * Reset when a real user/assistant turn adds substantial new content.
 */
export interface AutoCompactTracking {
  /** Token count at the time of the last compaction. */
  lastCompactTokenCount: number
  /** How many consecutive attempts were no-ops (already minimal). */
  consecutiveNoops: number
  /** Maximum allowed consecutive no-ops before disabling auto-compact. */
  maxNoops: number
}

export function createAutoCompactTracking(maxNoops: number = 3): AutoCompactTracking {
  return { lastCompactTokenCount: 0, consecutiveNoops: 0, maxNoops }
}

// ── Defaults ──

const MIN_TOKEN_DELTA_FOR_RECOMPACT = 5000 // Must add 5K tokens before re-compacting

// ── Core ──

/**
 * Check if auto-compaction is needed, considering hysteresis.
 *
 * Returns true only if:
 *   1. Token budget is exceeded (according to profile trigger ratio).
 *   2. No recent compaction was a no-op (consecutive noops < max).
 *   3. Sufficient new content has been added since the last compaction.
 */
export function shouldAutoCompact(
  messages: LLMMessage[],
  profile: AgentProfile,
  tracking?: AutoCompactTracking,
): boolean {
  const used = estimateMessagesTokens(messages)
  const budget = profile.context.budgets?.messages ?? 60000
  const triggerRatio = profile.context.compactTriggerRatio ?? 0.85

  // Basic budget check
  if (!isOverBudget(used, budget, triggerRatio)) return false

  // Hysteresis: don't compact if we're already minimal
  if (tracking && tracking.consecutiveNoops >= tracking.maxNoops) return false

  // Hysteresis: don't compact if not enough new content
  if (tracking && tracking.lastCompactTokenCount > 0) {
    const delta = used - tracking.lastCompactTokenCount
    if (delta < MIN_TOKEN_DELTA_FOR_RECOMPACT) return false
  }

  return true
}

/**
 * Update hysteresis tracking after a compaction attempt.
 *
 * @param tracking — tracking state to update
 * @param didCompact — whether compaction actually removed messages
 * @param currentTokens — current token count after compaction
 */
export function updateAutoCompactTracking(
  tracking: AutoCompactTracking,
  didCompact: boolean,
  currentTokens: number,
): void {
  if (didCompact) {
    tracking.lastCompactTokenCount = currentTokens
    tracking.consecutiveNoops = 0
  } else {
    tracking.consecutiveNoops++
  }
}

/**
 * Auto-compact conversation — keep recent N turns, LLM-summarize the rest.
 *
 * @param messages — current conversation messages
 * @param profile — agent profile (determines keepRecentTurns, budget)
 * @param existingSummary — previous compaction summary (concatenated if present)
 * @param opts — model override options
 */
export async function autoCompact(
  messages: LLMMessage[],
  profile: AgentProfile,
  existingSummary?: string,
  opts?: AutoCompactOptions,
): Promise<AutoCompactResult> {
  const keepCount = profile.context.keepRecentTurns * 2 // user + assistant per turn

  // Nothing to compact
  if (messages.length <= keepCount) {
    return {
      messages,
      summary: existingSummary || '',
      tokensFreed: 0,
      compressedCount: 0,
      didCompact: false,
    }
  }

  const toCompact = messages.slice(0, messages.length - keepCount)
  const toKeep = messages.slice(-keepCount)
  const beforeTokens = estimateMessagesTokens(messages)

  // Build compact prompt from messages to archive
  const compactInput = toCompact.map(m => {
    const role = m.role.toUpperCase()
    const content = typeof m.content === 'string'
      ? m.content
      : m.content.map(b => {
          if ((b as { type: string }).type === 'text') return (b as { text: string }).text
          if ((b as { type: string }).type === 'tool_use') return `[Tool: ${(b as { name: string }).name}]`
          if ((b as { type: string }).type === 'tool_result') return `[Tool Result: ${(b as { content: string }).content.slice(0, 200)}]`
          return ''
        }).join('\n')
    return `${role}: ${content.slice(0, COMPACT_MSG_TRUNCATE_CHARS)}`
  }).join('\n\n---\n\n')

  // Try LLM compact; fall back to truncation summary
  let summary = existingSummary || ''
  try {
    const provider = opts?.providerId
      ? modelProviderRegistry.getById(opts.providerId)
      : modelProviderRegistry.getDefault()

    if (provider) {
      let compactModel = opts?.compactModel
      if (!compactModel) {
        const llmConfig = loadLLMConfig(opts?.providerId)
        compactModel = llmConfig.provider
          ? new ModelResolver(llmConfig.provider).compact()
          : undefined
      }

      const result = await provider.chat({
        systemPrompt: COMPACT_SYSTEM_PROMPT,
        messages: [
          { role: 'user', content: compactInput },
          { role: 'user', content: COMPACT_USER_PROMPT },
        ],
        tools: [],
        model: compactModel,
      })

      const newSummary = result.content
        .filter((b): b is { type: 'text'; text: string } => b.type === 'text')
        .map(b => b.text)
        .join('\n')

      summary = existingSummary
        ? `${existingSummary}\n\n[Updated]\n${newSummary}`
        : newSummary
    }
  } catch (e) {
    console.warn(`[AutoCompactor] LLM compaction failed, falling back to truncation:`,
      e instanceof Error ? e.message : String(e))
    summary = `[Compacted ${toCompact.length} messages. ${existingSummary || ''}]`.trim()
  }

  // Build new message list
  const compactedMessages: LLMMessage[] = [
    { role: 'user', content: `[Previous conversation summary]\n${summary}` },
    ...toKeep,
  ]

  const afterTokens = estimateMessagesTokens(compactedMessages)

  return {
    messages: compactedMessages,
    summary,
    tokensFreed: Math.max(0, beforeTokens - afterTokens),
    compressedCount: toCompact.length,
    didCompact: true,
  }
}

// ── Convenience: check + compact in one call ──

/**
 * Check if compaction is needed and apply it. Combines shouldAutoCompact()
 * and autoCompact() into a single call. Returns null if no compaction needed.
 */
export async function autoCompactIfNeeded(
  messages: LLMMessage[],
  profile: AgentProfile,
  tracking?: AutoCompactTracking,
  existingSummary?: string,
  opts?: AutoCompactOptions,
): Promise<AutoCompactResult | null> {
  if (!shouldAutoCompact(messages, profile, tracking)) return null
  return autoCompact(messages, profile, existingSummary, opts)
}
