/**
 * ContextCompactor — Automatic context compression via LLM summarization.
 *
 * When the conversation approaches the token budget limit, early messages
 * are replaced with a structured summary generated by a dedicated LLM call.
 * Recent turns are preserved intact for continuity.
 */

import { estimateMessagesTokens, isOverBudget } from './token-counter'
import { COMPACT_SYSTEM_PROMPT, COMPACT_USER_PROMPT } from './compact-prompt'
import type { LLMMessage } from '../llm/LLMProvider'
import type { AgentProfile } from '../profile/AgentProfile'
import { llmProviderRegistry } from '../llm/LLMProviderRegistry'

export interface CompactResult {
  summary: string
  compactedMessages: LLMMessage[]
  tokenSaved: number
  compactedCount: number
}

/** Check if compaction is needed */
export function shouldCompact(
  messages: LLMMessage[],
  profile: AgentProfile,
): boolean {
  const used = estimateMessagesTokens(messages)
  return isOverBudget(
    used,
    profile.context.budgets.messages,
    profile.context.compactTriggerRatio,
  )
}

/** Compact conversation — keep recent N turns, summarize the rest */
export async function compactConversation(
  messages: LLMMessage[],
  profile: AgentProfile,
  existingSummary?: string,
): Promise<CompactResult> {
  const keepCount = profile.context.keepRecentTurns * 2 // user + assistant per turn
  if (messages.length <= keepCount) {
    return { summary: existingSummary || '', compactedMessages: messages, tokenSaved: 0, compactedCount: 0 }
  }

  const toCompact = messages.slice(0, messages.length - keepCount)
  const toKeep = messages.slice(-keepCount)
  const beforeTokens = estimateMessagesTokens(messages)

  // Build compact prompt
  const compactInput = toCompact.map(m => {
    const role = m.role.toUpperCase()
    const content = typeof m.content === 'string'
      ? m.content
      : m.content.map(b => {
          if (b.type === 'text') return b.text
          if (b.type === 'tool_use') return `[Tool: ${b.name}]`
          if (b.type === 'tool_result') return `[Tool Result: ${b.content.slice(0, 200)}]`
          return ''
        }).join('\n')
    return `${role}: ${content.slice(0, 2000)}`
  }).join('\n\n---\n\n')

  // Try LLM compact; fall back to simple truncation
  let summary = existingSummary || ''
  try {
    const provider = llmProviderRegistry.getDefault()
    if (provider) {
      const result = await provider.chat({
        systemPrompt: COMPACT_SYSTEM_PROMPT,
        messages: [
          { role: 'user', content: compactInput },
          { role: 'user', content: COMPACT_USER_PROMPT },
        ],
        tools: [],
      })
      summary = result.content
        .filter((b): b is { type: 'text'; text: string } => b.type === 'text')
        .map(b => b.text)
        .join('\n')
    }
  } catch {
    // LLM compact failed — fall back to truncation summary
    summary = `[Compacted ${toCompact.length} messages. ${existingSummary || ''}]`.trim()
  }

  // Build new message list: compact summary as system context + recent messages
  const compactedMessages: LLMMessage[] = [
    {
      role: 'user',
      content: `[Previous conversation summary]\n${summary}`,
    },
    ...toKeep,
  ]

  const afterTokens = estimateMessagesTokens(compactedMessages)

  return {
    summary,
    compactedMessages,
    tokenSaved: Math.max(0, beforeTokens - afterTokens),
    compactedCount: toCompact.length,
  }
}

// ── Microcompact: per-turn tool result size capping ──

const MAX_TOOL_RESULT_CHARS = 10_000

/** Compress individual tool results to avoid context bloat. Called per-turn before message append. */
export function microcompact(toolResults: { content: string }[]): { content: string }[] {
  return toolResults.map(tr => ({
    ...tr,
    content: tr.content.length > MAX_TOOL_RESULT_CHARS
      ? tr.content.slice(0, MAX_TOOL_RESULT_CHARS) + `\n...[truncated ${tr.content.length - MAX_TOOL_RESULT_CHARS} chars]`
      : tr.content,
  }))
}

// ── Reactive compaction: triggered on API 413 / prompt-too-long ──

/** Check if an API error is a context-length error (should trigger reactive compaction) */
export function isContextLengthError(err: unknown): boolean {
  const msg = (err as any)?.message || ''
  return msg.includes('prompt_too_long') || msg.includes('413') || msg.includes('context_length_exceeded')
}

/** Reactive compact — more aggressive than proactive. Keeps only keepRecentTurns/2 turns. */
export async function reactiveCompact(
  messages: LLMMessage[],
  profile: AgentProfile,
  existingSummary?: string,
): Promise<CompactResult> {
  // Halve the keep count for aggressive reactive compaction
  const keepCount = Math.max(2, Math.floor(profile.context.keepRecentTurns * 1.5)) // 1.5 turns (3 messages) minimum
  if (messages.length <= keepCount) {
    // Already minimal — just truncate tool results
    const compacted = messages.map(m => {
      if (typeof m.content === 'string') return m
      return { ...m, content: (m.content as any[]).map((b: any) => {
        if (b.type === 'tool_result' && b.content?.length > 5000) {
          return { ...b, content: b.content.slice(0, 5000) + '\n...[truncated]' }
        }
        return b
      })}
    })
    return { summary: existingSummary || '', compactedMessages: compacted, tokenSaved: 0, compactedCount: 0 }
  }

  // Aggressive: compact all but last keepCount messages
  return compactConversation(messages, { ...profile, context: { ...profile.context, keepRecentTurns: Math.ceil(keepCount / 2) } }, existingSummary)
}
