// Agent engine public API
export { AgentEventBus, agentEventBus } from './AgentEventBus'
export { AgentRuntime, agentRuntime } from './AgentRuntime'
export { ContextBuilder, contextBuilder } from './ContextBuilder'
export { AgentOrchestrator } from './orchestrator/AgentOrchestrator'
export type { AgentState, TerminalReason, RecoveryLevel } from './orchestrator/AgentState'
export { SubAgentManager, subAgentManager } from './subagent/SubAgentManager'
export type { SubAgentInfo, SubAgentResult } from './subagent/SubAgentManager'
export type { SubAgentContext } from './subagent/SubAgentContext'
export { validateProfile } from './profile/AgentProfile'
export type { AgentProfile } from './profile/AgentProfile'
export { renderPrompt } from './prompt/PromptTemplate'
export type { PromptTemplate, PromptSection, PromptContext } from './prompt/PromptTemplate'
export type { ModelProvider, LLMChatParams, LLMChatResult, LLMChunk, LLMChunkCallback } from './llm/ModelProvider'
export { LLMError } from './llm/ModelProvider'
export { AnthropicProvider } from './llm/AnthropicProvider'
export { ModelProviderRegistry, modelProviderRegistry } from './llm/ModelProviderRegistry'
export { createProvider } from './llm/ProviderFactory'
export { ModelResolver } from './llm/ModelResolver'
export { loadLLMConfig, listProviders, saveProvider, deleteProvider } from './llm/AttaSettingsLoader'
export type { LoadResult } from './llm/AttaSettingsLoader'
export type { ProviderDef, ResolvedProvider, SlotName } from './llm/ProviderDef'
export { SLOT_FALLBACK_CHAINS, SLOT_FIELD_NAMES } from './llm/ProviderDef'
export { orchestrateTools } from './tools/ToolOrchestrator'
export type { ToolExecResult, ToolOrchestrationResult } from './tools/ToolOrchestrator'
export { shouldCompact, compactConversation } from './compact/ContextCompactor'
export type { CompactResult } from './compact/ContextCompactor'
export { extractMemories } from './memory/MemoryExtractor'
export { loadFileMemories, toMemoryEntries } from './memory/FileMemory'
export type { FileMemoryEntry } from './memory/FileMemory'

// Profiles
export { codingProfile } from './profile/profiles/coding-profile'
export { researchProfile } from './profile/profiles/research-profile'
export { writingProfile } from './profile/profiles/writing-profile'

// Built-in sub-agent profiles
export { exploreAgentProfile } from './subagent/built-in/explore-agent'
export { planAgentProfile } from './subagent/built-in/plan-agent'
export { reviewAgentProfile } from './subagent/built-in/review-agent'
export { verifyAgentProfile } from './subagent/built-in/verify-agent'
